name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)
pool:
  vmImage: $(imageName)

pr:
  branches:
    include:
    - master
    - main
    - develop
    - refs/tags/v*
  paths:
    exclude:
    - docs/*
    - README.md

trigger:
  branches:
    include:
    - master
    - main
    - develop
    - refs/tags/v*
  paths:
    exclude:
    - docs/*
    - README.md

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      node_version: 10.x


steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- task: Npm@1
  inputs:
    command: 'install'

- script: npm run lint
  displayName: 'Lint'

- script: npm run build
  displayName: 'Build'

- script: npm run test
  displayName: 'Build'
  enabled: false

- script: ./publish.sh
  displayName: Publish
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))